Controllers/API/ShoesController.cs
using SportsEquipmentShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsEquipmentShop.Controllers.API
{
    public class ShoesController : Controller
    {
        ShoesDataContext datacontext = new ShoesDataContext();

     
        public ActionResult ShowShoes()
        {


            return View(datacontext.Shoes);

        }
        public ActionResult SortByPrice()
        {
            List<Shoe> shoes = datacontext.Shoes.OrderBy(item => item.price).ToList();
            return View(shoes);
        }

        public ActionResult managersTable()
        {

            return View(datacontext.Shoes);
        }

        public ActionResult IdentificationWindow()
        {

            return View();
        }
        public ActionResult OnSale()
        {


            return View(datacontext.Shoes);

        }
    }
}

Views/Shoes/IdentificationWindow.cshtml
<section id="SectionIdentification">

    


        <h1>welcome maneger!</h1>

        <label for="ID">Id</label>
        <input class="inputIdent" type="text" />

        <label for="password">Password</label>
        <input class="inputIdent" type="password" />


        <a href="@Url.Action("managersTable","Shoes")" class="btn"><button type="button">Enter</button></a>

  
</section>

Views/Shoes/OnSale.cshtml
@using SportsEquipmentShop.Models;

<h1 id="ShoeTitle">Sale!</h1>

<div class="SectionTshirts">
    <label for="Shoes">Sort By:</label>
    <select name="Shoes" id="shirtsSelect">
        <option class="options" value="choose">choose</option>
        <option class="options" value="true">cheap-expensive</option>
    </select>
    <button type="button" class="btnsort" onclick="location.href= '/Shoes/SortByPrice'">Sort</button>
</div>


<button onclick="location.href= '/Shoes/OnSale'" type="button" class="btnsort">Shoes On Sale</button>

<br />

@foreach (Shoe item in Model)
{
    if (@item.price < 200 || @item.price == 200)
    {
        <section id="ShooesData">
            <div>

                <p class="ShoeTitle">
                    @item.Company

                    @item.Model
                </p>

                <h4 class="ShoeTitle">  @item.price $</h4>

                <img id="ShoeImage" src=@item.image>


            </div>
        </section>
    }


}

Views/Shoes/ShowShoes.cshtml
@using SportsEquipmentShop.Models;


<h1 id="ShoeTitle">Sport Shoes</h1>

<div class="SectionTshirts">
    <label for="Shoes">Sort By:</label>
    <select name="Shoes" id="shirtsSelect">
        <option class="options" value="choose">choose</option>
        <option class="options" value="true">cheap-expensive</option>
    </select>
    <button type="button" class="btnsort" onclick="location.href= '/Shoes/SortByPrice'">Sort</button>
</div>


<button onclick="location.href= '/Shoes/OnSale'" class="btnsort" type="button">Shoes On Sale</button>

<br />

@foreach (Shoe item in Model)
{
    <section id="ShooesData">
        <div>

            <p class="ShoeTitle">
                @item.Company

                @item.Model
            </p>

            <h4 class="ShoeTitle">  @item.price $</h4>

            <img id="ShoeImage" src=@item.image>


        </div>
    </section>

}

<div id="ManagerBtn">
    <a href="@Url.Action("IdentificationWindow","Shoes")"><button type="button">Manager Page</button></a>

</div>

Views/Shoes/SortByPrice.cshtml
@using SportsEquipmentShop.Models;

<h1 id="ShoeTitle">Sport Shoes</h1>
<div class="SectionTshirts">
    <label for="Shoes">Sort By:</label>
    <select name="Shoes" id="shirtsSelect">
        <option class="options" value="choose">choose</option>

        <option class="options" value="true">cheap-expensive</option>
    </select>
    <button type="button" class="btnsort" onclick="location.href= '/Shoes/SortByPriceShoes'">Sort</button>
</div>


<button onclick="location.href= '/Shoes/OnSale'" class="btnsort" type="button">Shoes On Sale</button>
<br />

@foreach (Shoe item in Model)
{
    <section id="ShooesData">
        <div>

            <p class="ShoeTitle">
                @item.Company

                @item.Model
            </p>

            <h4 class="ShoeTitle">  @item.price $</h4>

            <img id="ShoeImage" src=@item.image>


        </div>
    </section>

}

Views/Shoes/managersTable.cshtml
@using SportsEquipmentShop.Models;


<section id="TableSection">
    <h1 id="ShoeTitle">All Shoes</h1>
    <table>
        <tr>
            <th>Id</th>
            <th>Shoe Type</th>
            <th>Company</th>
            <th>Model</th>
            <th>Price</th>
            <th>Amount</th>
            <th>Image</th>
        </tr>

        @foreach (Shoe item in Model)
        {

            <tr>
                <td>@item.Id</td>
                <td>@item.ShoeType</td>
                <td> @item.Company</td>
                <td> @item.Model</td>
                <td> @item.price $ </td>
                <td>@item.Amount</td>
                <td><img src=@item.image style="width:100px"></td>
            </tr>

        }
    </table>
    </section>