Controllers/API/SportsEquipmentController.cs
using SportsEquipmentShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsEquipmentShop.Controllers.API
{
    public class SportsEquipmentController : Controller
    {

        ShoesDataContext datacontext = new ShoesDataContext();

        public ActionResult ShowAllSportsEquipments()
        {
            return View(datacontext.SportsEquipments);
        }
        public ActionResult IdentificationEquipment()
        {
            return View(datacontext.SportsEquipments);

        }
        
        public ActionResult managersTableEquipment()
        {
            return View(datacontext.SportsEquipments);

        }
        public ActionResult OnlyFootball()
        {
            return View(datacontext.SportsEquipments);

        }
        public ActionResult OnlyBasketball()
        {
            return View(datacontext.SportsEquipments);

        }
        public ActionResult SortByPrice()
        {
            List<SportsEquipment> SportE = datacontext.SportsEquipments.OrderBy(item => item.price).ToList();
            return View(SportE);
        }
    }
}

Views/SportsEquipment/IdentificationEquipment.cshtml
<section id="SectionIdentification">




    <h1>welcome maneger!</h1>

    <label for="ID">Id</label>
    <input class="inputIdent" type="text" />

    <label for="password">Password</label>
    <input class="inputIdent" type="password" />


    <a href="@Url.Action("managersTableEquipment","SportsEquipment")" class="btn"><button type="button">Enter</button></a>


</section>

Views/SportsEquipment/OnlyBasketball.cshtml
@using SportsEquipmentShop.Models;

<h1 id="ShoeTitle">Sport Equipment</h1>

<div class="SectionTshirts">
    <label for="shirts">Sort By:</label>
    <select name="shirts" id="shirtsSelect">
        <option class="options" value="choose">choose</option>
        <option class="options" value="cheap-expensive">cheap-expensive</option>
    </select>
    <button type="button" class="btnsort" onclick="location.href= '/SportsEquipment/SortByPrice'">Sort</button>
</div>


<a><label onclick="location.href= '/SportsEquipment/OnlyFootball'"><input id="Test" name="Test" type="checkbox" value="true"> Football </label></a>
<a><label onclick="location.href= '/SportsEquipment/OnlyBasketball'"><input id="Test" name="Test" type="checkbox" value="true"> Basketball </label></a>
<br />

@foreach (SportsEquipment item in Model)
{
    if (item.sport == "basketball")
    {

        <section id="ShooesData">
            <div>

                <p class="ShoeTitle">
                    @item.company

                    @item.ProductName
                </p>

                <h4 class="ShoeTitle">  @item.price $</h4>

                <img id="ShoeImage" src=@item.image>

            </div>
        </section>
    }
}

Views/SportsEquipment/OnlyFootball.cshtml
@using SportsEquipmentShop.Models;

<h1 id="ShoeTitle">Sport Equipment</h1>

<div class="SectionTshirts">
    <label for="shirts">Sort By:</label>
    <select name="shirts" id="shirtsSelect">
        <option class="options" value="choose">choose</option>
        <option  class="options"  value="cheap-expensive">cheap-expensive</option>
    </select>
    <button type="button" class="btnsort"  onclick="location.href= '/SportsEquipment/SortByPrice'">Sort</button>
</div>


<a><label onclick="location.href= '/SportsEquipment/OnlyFootball'"><input id="Test" name="Test" type="checkbox" value="true"> Football </label></a>
<a><label onclick="location.href= '/SportsEquipment/OnlyBasketball'"><input id="Test" name="Test" type="checkbox" value="true"> Basketball </label></a>
<br />


@foreach (SportsEquipment item in Model)
{
    if (item.sport == "football")
    {

        <section id="ShooesData">
            <div>

                <p class="ShoeTitle">
                    @item.company

                    @item.ProductName
                </p>

                <h4 class="ShoeTitle">  @item.price $</h4>

                <img id="ShoeImage" src=@item.image>

            </div>
        </section>
    }
}

Views/SportsEquipment/ShowAllSportsEquipments.cshtml
@using SportsEquipmentShop.Models;


<h1 id="ShoeTitle">Sport Equipment</h1>

<div class="SectionTshirts">
    <label for="shirts">Sort By:</label>
    <select name="shirts" id="shirtsSelect">
        <option class="options" value="choose">choose</option>
        <option class="options" value="cheap-expensive">cheap-expensive</option>
    </select>
    <button type="button" class="btnsort" onclick="location.href= '/SportsEquipment/SortByPrice'">Sort</button>
</div>


<a><label onclick="location.href= '/SportsEquipment/OnlyFootball'"><input id="Test" name="Test" type="checkbox" value="true"> Football </label></a>
<a><label onclick="location.href= '/SportsEquipment/OnlyBasketball'"><input id="Test" name="Test" type="checkbox" value="true"> Basketball </label></a>
<br />

@foreach (SportsEquipment item in Model)
{

    <section id="ShooesData">
        <div>

            <p class="ShoeTitle">
                @item.company

                @item.ProductName
            </p>

            <h4 class="ShoeTitle">  @item.price $</h4>

            <img id="ShoeImage" src=@item.image>

        </div>
    </section>
}

<div id="ManagerBtn">
    <a href="@Url.Action("IdentificationEquipment","SportsEquipment")"><button type="button">Manager Page</button></a>
</div>

Views/SportsEquipment/SortByPrice.cshtml
@using SportsEquipmentShop.Models;


<h1 id="ShoeTitle">Sport Equipment</h1>

<div class="SectionTshirts">
    <label for="shirts">Sort By:</label>
    <select name="shirts" id="shirtsSelect">
        <option class="options" value="choose">choose</option>
        <option class="options" value="cheap-expensive">cheap-expensive</option>
    </select>
    <button type="button" class="btnsort" onclick="location.href= '/SportsEquipment/SortByPrice'">Sort</button>
</div>


<a><label onclick="location.href= '/SportsEquipment/OnlyFootball'"><input id="Test" name="Test" type="checkbox" value="true"> Football </label></a>
<a><label onclick="location.href= '/SportsEquipment/OnlyBasketball'"><input id="Test" name="Test" type="checkbox" value="true"> Basketball </label></a>
<br />

@foreach (SportsEquipment item in Model)
{


    <section id="ShooesData">
        <div>

            <p class="ShoeTitle">
                @item.company

                @item.ProductName
            </p>

            <h4 class="ShoeTitle">  @item.price $</h4>

            <img id="ShoeImage" src=@item.image>

        </div>
    </section>
}

Views/SportsEquipment/managersTableEquipment.cshtml
@using SportsEquipmentShop.Models;


<section id="TableSection">
    <h1 id="ShoeTitle">All Equipment</h1>
    <table>
        <tr>
            <th>Id</th>
            <th>Sport</th>
            <th>ProductName</th>
            <th>Company</th>
            <th>Price</th>
            <th>Amount</th>
            <th>TeamId</th>
            <th>Image</th>



        </tr>

        @foreach (SportsEquipment item in Model)
        {
           
                <tr>
                    <td>@item.Id</td>
                    <td>@item.sport</td>
                    <td> @item.ProductName</td>
                    <td> @item.company</td>
                    <td> @item.price $ </td>
                    <td>@item.amount</td>
                    <td>@item.TeamId</td>
                    <td><img src=@item.image style="width:100px"></td>
                </tr>
         

        }
    </table>
</section>