Controllers/API/ClothingController.cs
using SportsEquipmentShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsEquipmentShop.Controllers.API
{
    public class ClothingController : Controller
    {
        ShoesDataContext datacontext = new ShoesDataContext();

        public ActionResult ShowAllTshirt()
        {
            return View(datacontext.Clothings);
        }


        public ActionResult managersTableShirts()
        {
            return View(datacontext.Clothings);
        }

        public ActionResult IdentificationWindow()
        {
            return View();
        }
        public ActionResult LongTshirt()
        {

            return View(datacontext.Clothings);
        }

        public ActionResult DryFitShirts()
        {

            return View(datacontext.Clothings);
        }
        public ActionResult SortByPrice()
        {
            List<Clothing> clothings = datacontext.Clothings.OrderBy(item => item.price).ToList();
            return View(clothings);
        }

        public ActionResult TShirts()
        {
            return View(datacontext.Clothings);

        }

        public ActionResult ShowAllPants()
        {
            return View(datacontext.Clothings);
        }

        public ActionResult managersTablePants()
        {
            return View(datacontext.Clothings);
        }
        public ActionResult IdentificationPants()
        {
            return View();
        }
        public ActionResult LongPants()
        {
            return View(datacontext.Clothings);
        }
        public ActionResult ShortPants()
        {
            return View(datacontext.Clothings);

        }
        public ActionResult DryFitPants()
        {
            return View(datacontext.Clothings);

        }
        public ActionResult SortByPricePants()
        {
            List<Clothing> clothes = datacontext.Clothings.OrderBy(item => item.price).ToList();
            return View(clothes);

        }
        public ActionResult AllWomen()
        { 
            return View(datacontext.Clothings);

        }
        public ActionResult Allmen()
        {
            return View(datacontext.Clothings);

        }

    }
}

Views/Clothing/AllWomen.cshtml
@using SportsEquipmentShop.Models;

<h1 id="ShoeTitle">women</h1>


@foreach (Clothing item in Model)
{
    if (item.gender == "women")
    {

        <section id="ShooesData">
            <div>

                <p class="ShoeTitle">
                    @item.company

                    @item.TypeOfClothes
                </p>

                <h4 class="ShoeTitle">  @item.price $</h4>

                <img id="ShoeImage" src=@item.image>

            </div>
        </section>
    }
}

Views/Clothing/Allmen.cshtml
@using SportsEquipmentShop.Models;

<h1 id="ShoeTitle">men</h1>



@foreach (Clothing item in Model)
{
    if (item.gender == "men")
    {

        <section id="ShooesData">
            <div>

                <p class="ShoeTitle">
                    @item.company

                    @item.TypeOfClothes
                </p>

                <h4 class="ShoeTitle">  @item.price $</h4>

                <img id="ShoeImage" src=@item.image>

            </div>
        </section>
    }
}

Views/Clothing/DryFitShirts.cshtml
@using SportsEquipmentShop.Models;

<h1 id="ShoeTitle">Sport shirts</h1>

<div class="SectionTshirts">
    <label for="shirts">Sort By:</label>
    <select name="shirts" id="shirtsSelect">
        <option class="options" value="choose">choose</option>
        <option class="options" value="true">cheap-expensive</option>
    </select>
    <button type="button"  class="btnsort" onclick="location.href= '/Clothing/SortByPrice'">Sort</button>
</div>

<a><label onclick="location.href= '/Clothing/LongTshirt'"><input type="checkbox" value="true"> Long Shirts</label></a>
<a><label onclick="location.href= '/Clothing/TShirts'"><input type="checkbox" value="true">TShirts</label></a>

<a><label onclick="location.href= '/Clothing/DryFitShirts'"><input type="checkbox" value="true"> DryFit Shirts</label></a>


<br />


@foreach (Clothing item in Model)
{
    if (item.DryFit_ == true && item.TypeOfClothes=="shirt")
    {
        <section id="ShooesData">
            <div>

                <p class="ShoeTitle">
                    @item.company

                    @item.TypeOfClothes
                </p>

                <h4 class="ShoeTitle">  @item.price $</h4>

                <img id="ShoeImage" src=@item.image>

            </div>
        </section>
    }
}

Views/Clothing/IdentificationPants.cshtml
<section id="SectionIdentification">




    <h1>welcome maneger!</h1>

    <label for="ID">Id</label>
    <input class="inputIdent" type="text" />

    <label for="password">Password</label>
    <input class="inputIdent" type="password" />


    <a href="@Url.Action("managersTablePants","Clothing")" class="btn"><button type="button">Enter</button></a>


</section>

Views/Clothing/IdentificationWindow.cshtml
<section id="SectionIdentification">




    <h1>welcome maneger!</h1>

    <label for="ID">Id</label>
    <input class="inputIdent" type="text" />

    <label for="password">Password</label>
    <input class="inputIdent" type="password" />


    <a href="@Url.Action("managersTableShirts","Clothing")" class="btn"><button type="button">Enter</button></a>


</section>

Views/Clothing/LongPants.cshtml
@using SportsEquipmentShop.Models;
<h1 id="ShoeTitle">Sport pants</h1>

<div class="SectionTshirts">
    <label for="shirts">Sort By:</label>
    <select name="shirts" id="shirtsSelect">
        <option class="options" value="choose">choose</option>
        <option class="options" value="cheap-expensive">cheap-expensive</option>
    </select>
    <button class="btnsort"  type="button">Sort</button>
</div>


<a><label onclick="location.href= '/Clothing/LongPants'"><input type="checkbox" value="true"> Long Pants</label></a>
<a><label onclick="location.href= '/Clothing/ShortPants'"><input type="checkbox" value="true"> Short Pants</label></a>
<a><label onclick="location.href= '/Clothing/DryFitPants'"><input type="checkbox" value="true"> DryFit Pants</label></a>

<br />


@foreach (Clothing item in Model)
{
    if (item.t_shirt_ == false && item.TypeOfClothes == "pants" )
    {
        <section id="ShooesData">
            <div>

                <p class="ShoeTitle">
                    @item.company

                    @item.TypeOfClothes
                </p>

                <h4 class="ShoeTitle">  @item.price $</h4>

                <img id="ShoeImage" src=@item.image>

            </div>
        </section>
    }
}

Views/Clothing/LongTshirt.cshtml
@using SportsEquipmentShop.Models;

<h1 id="ShoeTitle">Sport shirts</h1>

<div class="SectionTshirts">
    <label for="shirts">Sort By:</label>
    <select name="shirts" id="shirtsSelect">
        <option class="options" value="choose">choose</option>
        <option class="options" value="true">cheap-expensive</option>
    </select>
    <button type="button" class="btnsort" onclick="location.href= '/Clothing/SortByPrice'">Sort</button>
</div>

<a><label onclick="location.href= '/Clothing/LongTshirt'"><input type="checkbox" value="true"> Long Shirts</label></a>
<a><label onclick="location.href= '/Clothing/TShirts'"><input type="checkbox" value="true">TShirts</label></a>

<a><label onclick="location.href= '/Clothing/DryFitShirts'"><input type="checkbox" value="true"> DryFit Shirts</label></a>


<br />

@foreach (Clothing item in Model)
{
    if (item.t_shirt_ == false && item.TypeOfClothes == "shirt")
    {
        <section id="ShooesData">
            <div>

                <p class="ShoeTitle">
                    @item.company

                    @item.TypeOfClothes
                </p>

                <h4 class="ShoeTitle">  @item.price $</h4>

                <img id="ShoeImage" src=@item.image>

            </div>
        </section>
    }
}

Views/Clothing/ShortPants.cshtml
@using SportsEquipmentShop.Models;
<h1 id="ShoeTitle">Sport pants</h1>

<div class="SectionTshirts">
    <label for="shirts">Sort By:</label>
    <select name="shirts" id="shirtsSelect">
        <option class="options" value="choose">choose</option>
        <option class="options" value="cheap-expensive">cheap-expensive</option>
    </select>
    <button type="button" class="btnsort" >Sort</button>
</div>


<a><label onclick="location.href= '/Clothing/LongPants'"><input type="checkbox" value="true"> Long Pants</label></a>
<a><label onclick="location.href= '/Clothing/ShortPants'"><input type="checkbox" value="true"> Short Pants</label></a>
<a><label onclick="location.href= '/Clothing/DryFitPants'"><input type="checkbox" value="true"> DryFit Pants</label></a>

<br />


@foreach (Clothing item in Model)
{
    if (item.TypeOfClothes == "pants" && item.t_shirt_ == true)
    {
        <section id="ShooesData">
            <div>

                <p class="ShoeTitle">
                    @item.company

                    @item.TypeOfClothes
                </p>

                <h4 class="ShoeTitle">  @item.price $</h4>

                <img id="ShoeImage" src=@item.image>

            </div>
        </section>
    }
}

Views/Clothing/ShowAllPants.cshtml
@using SportsEquipmentShop.Models;

<h1 id="ShoeTitle">Sport pants</h1>

<div class="SectionTshirts">
    <label for="shirts">Sort By:</label>
    <select name="shirts" id="shirtsSelect">
        <option class="options" value="choose">choose</option>
        <option class="options" value="cheap-expensive">cheap-expensive</option>
    </select>
    <button type="button" class="btnsort" onclick="location.href= '/Clothing/SortByPricePants'">Sort</button>
</div>


<a><label onclick="location.href= '/Clothing/LongPants'"><input  type="checkbox" value="true"> Long Pants</label></a>
<a><label onclick="location.href= '/Clothing/ShortPants'"><input  type="checkbox" value="true"> Short Pants</label></a>
<a><label onclick="location.href= '/Clothing/DryFitPants'"><input  type="checkbox" value="true"> DryFit Pants</label></a>

<br />


@foreach (Clothing item in Model)
{
    if (item.TypeOfClothes == "pants")
    {
        <section id="ShooesData">
            <div>

                <p class="ShoeTitle">
                    @item.company

                    @item.TypeOfClothes
                </p>

                <h4 class="ShoeTitle">  @item.price $</h4>

                <img id="ShoeImage" src=@item.image>

            </div>
        </section>
    }

}

<div id="ManagerBtn">
    <a href="@Url.Action("IdentificationPants","Clothing")"><button type="button">Manager Page</button></a>

</div>

Views/Clothing/ShowAllTshirt.cshtml
@using SportsEquipmentShop.Models;


<h1 id="ShoeTitle">Sport shirts</h1>

<div class="SectionTshirts">
    <label for="shirts">Sort By:</label>
    <select name="shirts" id="shirtsSelect">
        <option class="options" value="choose">choose</option>
        <option class="options" value="true">cheap-expensive</option>
    </select>
    <button type="button" class="btnsort" onclick="location.href= '/Clothing/SortByPrice'">Sort</button>
</div>

<a><label onclick="location.href= '/Clothing/LongTshirt'"><input type="checkbox" value="true"> Long Shirts</label></a>
<a><label onclick="location.href= '/Clothing/TShirts'"><input type="checkbox" value="true">TShirts</label></a>

<a><label onclick="location.href= '/Clothing/DryFitShirts'"><input type="checkbox" value="true"> DryFit Shirts</label></a>


<br />

@foreach (Clothing item in Model)
{
    if (item.TypeOfClothes == "shirt")
    {
        <section id="ShooesData">
            <div>

                <p class="ShoeTitle">
                    @item.company

                    @item.TypeOfClothes
                </p>

                <h4 class="ShoeTitle">  @item.price $</h4>

                <img id="ShoeImage" src=@item.image>

            </div>
        </section>
    }

}

<div id="ManagerBtn">
    <a href="@Url.Action("IdentificationWindow","Clothing")"><button type="button">Manager Page</button></a>

</div>

Views/Clothing/SortByPricePants.cshtml
@using SportsEquipmentShop.Models;

<h1 id="ShoeTitle">Sport pants</h1>

<div class="SectionTshirts">
    <label for="shirts">Sort By:</label>
    <select name="shirts" id="shirtsSelect">
        <option class="options" value="choose">choose</option>
        <option class="options" value="cheap-expensive">cheap-expensive</option>
    </select>
    <button type="button" class="btnsort" onclick="location.href= '/Clothing/SortByPricePants'">Sort</button>
</div>


<a><label onclick="location.href= '/Clothing/LongPants'"><input type="checkbox" value="true"> Long Pants</label></a>
<a><label onclick="location.href= '/Clothing/ShortPants'"><input type="checkbox" value="true"> Short Pants</label></a>
<a><label onclick="location.href= '/Clothing/DryFitPants'"><input type="checkbox" value="true"> DryFit Pants</label></a>

<br />



@foreach (Clothing item in Model)
{
    if (item.TypeOfClothes == "pants")
    {
        <section id="ShooesData">
            <div>

                <p class="ShoeTitle">
                    @item.company

                    @item.TypeOfClothes
                </p>

                <h4 class="ShoeTitle">  @item.price $</h4>

                <img id="ShoeImage" src=@item.image>

            </div>
        </section>


    }
}

Views/Clothing/TShirts.cshtml
@using SportsEquipmentShop.Models;

<h1 id="ShoeTitle">Sport shirts</h1>


<div class="SectionTshirts">
    <label for="shirts">Sort By:</label>
    <select name="shirts" id="shirtsSelect">
        <option class="options" value="choose">choose</option>
        <option class="options" value="true">cheap-expensive</option>
    </select>
    <button type="button" class="btnsort" onclick="location.href= '/Clothing/SortByPrice'">Sort</button>
</div>

<a><label onclick="location.href= '/Clothing/LongTshirt'"><input type="checkbox" value="true"> Long Shirts</label></a>
<a><label onclick="location.href= '/Clothing/TShirts'"><input type="checkbox" value="true">TShirts</label></a>

<a><label onclick="location.href= '/Clothing/DryFitShirts'"><input type="checkbox" value="true"> DryFit Shirts</label></a>


<br />
@foreach (Clothing item in Model)
{
    if (item.t_shirt_ == true && item.TypeOfClothes == "shirt")
    {
        <section id="ShooesData">
            <div>

                <p class="ShoeTitle">
                    @item.company

                    @item.TypeOfClothes
                </p>

                <h4 class="ShoeTitle">  @item.price $</h4>

                <img id="ShoeImage" src=@item.image>

            </div>
        </section>
    }
}

Views/Clothing/managersTablePants.cshtml
@using SportsEquipmentShop.Models;


<section id="TableSection">
    <h1 id="ShoeTitle">All Shoes</h1>
    <table>
        <tr>
            <th>Id</th>
            <th>Type Of Clothes</th>
            <th>Gender</th>
            <th>Company</th>
            <th>Model</th>
            <th>Price</th>
            <th>Amount</th>
            <th>t-shirt</th>
            <th>Dry-Fit</th>
            <th>Image</th>



        </tr>

        @foreach (Clothing item in Model)
        {
            if (item.TypeOfClothes == "pants")
            {

                <tr>
                    <td>@item.Id</td>
                    <td>@item.TypeOfClothes</td>
                    <td> @item.gender</td>
                    <td> @item.company</td>
                    <td> @item.model</td>
                    <td> @item.price $ </td>
                    <td>@item.amount</td>
                    <td>@item.t_shirt_</td>
                    <td>@item.DryFit_</td>
                    <td><img src=@item.image style="width:100px"></td>
                </tr>
            }

        }
    </table>
</section>

Views/Clothing/managersTableShirts.cshtml
@using SportsEquipmentShop.Models;


<section id="TableSection">
    <h1 id="ShoeTitle">All Shoes</h1>
    <table>
        <tr>
            <th>Id</th>
            <th>Type Of Clothes</th>
            <th>Gender</th>
            <th>Company</th>
            <th>Model</th>
            <th>Price</th>
            <th>Amount</th>
            <th>t-shirt</th>
            <th>Dry-Fit</th>
            <th>Image</th>



        </tr>

        @foreach (Clothing item in Model)
        {
            if (item.TypeOfClothes == "shirt")
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.TypeOfClothes</td>
                    <td> @item.gender</td>
                    <td> @item.company</td>
                    <td> @item.model</td>
                    <td> @item.price $ </td>
                    <td>@item.amount</td>
                    <td>@item.t_shirt_</td>
                    <td>@item.DryFit_</td>
                    <td><img src=@item.image style="width:100px"></td>
                </tr>
            }

        }
    </table>
</section>